const fortunes = {
  "Love": [
    "your heart will shine brightly today.",
    "someone will be deeply moved by your kindness.",
    "love will find you when you least expect it.",
    "a gentle smile will open someone’s heart today.",
    "your warmth will comfort someone close to you.",
    "today is a day to express affection freely.",
    "an old bond will be rekindled with affection.",
    "a heartfelt message will reach you soon.",
    "your sincerity will attract good energy.",
    "someone will quietly admire your caring nature."
  ],
  "Wisdom": [
    "clarity will guide your thoughts today.",
    "trust your insight — it will lead you to peace.",
    "your mind will find an answer hidden in silence.",
    "a new perspective will solve an old question.",
    "you will offer advice that helps someone grow.",
    "a thoughtful word from you will inspire others.",
    "patience will reveal what knowledge cannot.",
    "your wisdom will bring calm to those around you.",
    "listen before speaking — the truth will emerge.",
    "today, your insight will light the way forward."
  ],
  "Harmony": [
    "balance will return where there was tension.",
    "your calm presence will unite those around you.",
    "a peaceful solution will appear effortlessly.",
    "your honesty will bridge a quiet misunderstanding.",
    "cooperation will come naturally today.",
    "a conversation will restore peace of mind.",
    "your steadiness brings comfort to others.",
    "you will find beauty in simple balance.",
    "today, harmony follows your every word.",
    "you’ll notice peace in the smallest details."
  ],
  "Hope": [
    "a new light will show the way forward.",
    "someone’s words will lift your spirits today.",
    "your hope will inspire someone who’s struggling.",
    "good news will arrive sooner than expected.",
    "even the smallest step today will bring progress.",
    "a bright change begins with your positive thought.",
    "keep faith — what you dream is already taking shape.",
    "a sign of renewal will surprise you today.",
    "the future feels clearer because you believed.",
    "your optimism will shape the energy around you."
  ],
  "Peace": [
    "stillness will soothe your thoughts today.",
    "a quiet moment will restore your energy.",
    "the world feels softer when you breathe deeply.",
    "your calmness will influence others positively.",
    "a peaceful encounter will warm your day.",
    "patience will bring serenity into your heart.",
    "your gentle words will prevent a conflict.",
    "a brief silence will heal what was heavy.",
    "you’ll sense peace in unexpected places.",
    "inner balance will follow your calm decisions."
  ],
  "Kindness": [
    "a small favor today will grow into deep gratitude.",
    "your kindness will be repaid in ways you don’t expect.",
    "a stranger will smile because of your action.",
    "your empathy will guide someone out of sadness.",
    "a gentle gesture will speak louder than words.",
    "you will be reminded of the beauty of giving.",
    "your patience will heal someone’s heart today.",
    "a good deed from the past will circle back warmly.",
    "compassion will make your day brighter.",
    "the universe will mirror your gentle heart."
  ],
  "Light": [
    "your light will guide others through uncertainty.",
    "today’s moments will sparkle with clarity.",
    "someone will see hope through your energy.",
    "you’ll brighten another’s path without knowing it.",
    "your positivity will light up the room.",
    "truth will reveal itself through your patience.",
    "the day’s glow matches your calm strength.",
    "you will notice brightness even in quiet spaces.",
    "your presence will feel like a sunrise to others.",
    "light will follow you wherever you go today."
  ],
  "Growth": [
    "a challenge will strengthen your spirit.",
    "you will grow quietly, even without noticing.",
    "patience will turn into progress soon.",
    "your consistency will be rewarded today.",
    "you’ll learn something important through experience.",
    "your maturity will impress someone new.",
    "growth may feel slow, but every step counts.",
    "today’s small effort plants tomorrow’s success.",
    "you will overcome a limit you once believed fixed.",
    "every lesson today shapes your better self."
  ],
  "Faith": [
    "trust the process — it’s unfolding perfectly.",
    "a moment of doubt will turn into belief.",
    "something uncertain will soon make sense.",
    "your faith will reassure someone else.",
    "you’ll feel protected in ways you can’t see.",
    "a sign will affirm that you’re on the right path.",
    "what you’ve hoped for begins to manifest today.",
    "confidence in yourself will quiet your worries.",
    "you’ll feel peace after letting go of control.",
    "your belief will move an obstacle aside."
  ],
  "Joy": [
    "laughter will fill your day unexpectedly.",
    "a surprise will lift your heart.",
    "today is a reminder that happiness is simple.",
    "joy will come from a small act of gratitude.",
    "you’ll share smiles with people who care for you.",
    "a playful spirit will brighten your mood.",
    "you’ll rediscover something that once made you happy.",
    "today’s energy will feel light and cheerful.",
    "someone’s joy will reflect your own warmth.",
    "good memories will visit you when you least expect."
  ],
  "Beauty": [
    "you’ll see beauty where others see ordinary things.",
    "aesthetic harmony will bring you peace today.",
    "your charm will attract positive attention.",
    "you’ll create something lovely without effort.",
    "someone will compliment your natural grace.",
    "a detail you notice will inspire creativity.",
    "you’ll rediscover joy in something beautiful.",
    "today’s light will reveal colors you’ve missed.",
    "your calm aura will feel captivating to others.",
    "you’ll find elegance in life’s simplest rhythm."
  ],
  "Strength": [
    "your resilience will shine brighter than ever.",
    "today, courage will replace hesitation.",
    "a challenge will prove how capable you’ve become.",
    "you’ll feel power in your quiet confidence.",
    "someone will rely on your inner strength today.",
    "your endurance will carry you through with grace.",
    "you’ll notice how far you’ve already come.",
    "strength will flow naturally from your calm focus.",
    "even in silence, your resolve will be felt.",
    "today is a day to stand tall and proud of yourself."
  ]
};
